### ISSUE TITLE
Toast is not displayed for the first time

### ISSUE THREAD

**Issue by germanberselli** [PointInside/ng2-toastr#118] opened 2017-01-11 16:22 UTC
I'm using angular 2.2.4 with this seed "https://github.com/mgechev/angular-seed" and I included the styles on head (link rel="stylesheet" href="/node_modules/ng2-toastr/bundles/ng2-toastr.min.css") but the first time that I enter to the page and tried to show a toastr, the toastr is not displayed. But if I reload the page and I do the same steps the toastr is shown correctly. Any ideas?

PS: I tried also copy the ng2-toastr.css to my app styles and the behaviour is the same. Maybe is realted to the way the is included the toastr component the first time.

ng2-toastr version: 1.3.4

**Comment by bonaparte89** [comment] 2017-01-13 14:59
you want to load them in your project.config.ts
/tools/config/project.config.ts 
{src: 'ng2-toastr/bundles/ng2-toastr.min.css', inject: true}

works for me

**Comment by germanberselli** [comment] 2017-01-13 15:06
yes, I added the load in project.config.ts. and the issue persist. I think that is not related with the css, because the stylesheet is properly loaded.

**Comment by derekshi** [comment] 2017-02-24 21:44
Close this due to lack of code details or reproduce steps.

**Closed by derekshi** 2017-02-24 21:44 UTC
