### ISSUE TITLE
Uncaught Can't resolve all parameters for ToastContainer: (?, ToastOptions).

### ISSUE THREAD

**Issue by jadav1982** [PointInside/ng2-toastr#47] opened 2016-09-10 10:03 UTC
I am getting below error. I have used ng2-toastr@0.4.1.
zone.js:269 Uncaught Can't resolve all parameters for ToastContainer: (?, ToastOptions).

I have followed instantiation which in below link.

https://www.npmjs.com/package/ng2-toastr

Thanks,
Tarun

**Comment by derekshi** [comment] 2016-09-12 23:55
I think the issue is in rc.6, Angular team renamed DomSanitizer. So make sure your angular 2 version is rc.6, not rc.5. Please let me know if upgrading to rc.6 solves your problem.

**Comment by derekshi** [comment] 2016-09-12 23:57
I am closing this issue because it's duplicate #46

**Closed by derekshi** 2016-09-12 23:57 UTC
